export default {
  Announcements: 'Объявления',
  Accessibility: 'Доступность',
  AirPlay: 'AirPlay',
  Audio: 'Аудио',
  Auto: 'Авто',
  Boost: 'Увеличить',
  Captions: 'Титры',
  'Caption Styles': 'Стили титров',
  'Captions look like this': 'Предпросмотр стилей титров',
  Chapters: 'Главы',
  'Closed-Captions Off': 'Выключить субтитры',
  'Closed-Captions On': 'Включить субтитры',
  Connected: 'Подключено',
  Continue: 'Продолжить',
  Connecting: 'Подключение',
  Default: 'По умолчанию',
  Disabled: 'Отключено',
  Disconnected: 'Нет связи',
  'Display Background': 'Фон отображения',
  Download: 'Скачать',
  'Enter Fullscreen': 'Во весь экран',
  'Enter PiP': 'В мини-окне',
  'Exit Fullscreen': 'Выйти из полноэкранного режима',
  'Exit PiP': 'Вернуться в обычное окно',
  Font: 'Шрифт',
  Family: 'Семейство',
  Fullscreen: 'Полноэкранный',
  'Google Cast': 'Google Cast',
  'Keyboard Animations': 'Анимация клавиатуры',
  LIVE: 'LIVE',
  Loop: 'Зациклить',
  Mute: 'Выключить звук',
  Normal: 'Норма',
  Off: 'Выкл',
  Pause: 'Пауза',
  Play: 'Воспроизвести',
  Playback: 'Воспроизведение',
  PiP: 'Картинка в картинке',
  Quality: 'Качество',
  Replay: 'Повторить',
  Reset: 'Сброс',
  'Seek Backward': 'Назад на 10 секунд',
  'Seek Forward': 'Вперёд на 10 секунд',
  Seek: 'Перемотка',
  Settings: 'Настройки',
  'Skip To Live': 'Перейти к прямой трансляции',
  Speed: 'Скорость',
  Size: 'Размер',
  Color: 'Цвет',
  Opacity: 'Прозрачность',
  Shadow: 'Тень',
  Text: 'Текст',
  'Text Background': 'Фон текста',
  Track: 'Трек',
  Unmute: 'Включить звук',
  Volume: 'Громкость',
}
