export default {
  project: 'Orbita',
  actions: {
    save: 'Save',
    submit: 'Submit',
    cancel: 'Cancel',
    close: 'Close',
    delete: 'Delete',
    create: 'Create',
    edit: 'Edit',
    add: 'Add',
    view: 'View',
    levels: {
      manage: 'Manage subscriptions',
      subscribe: 'Subscribe',
      subscribed: 'Subscribed',
    },
  },
  security: {
    login: 'Login',
    logout: 'Logout',
    register: 'Register',
    reset: 'Forgot password',
    reset_desc: `You can request a one-time link to log in to your account. After logging in, you will be able to change your old password.`,
  },
  models: {
    user: {
      title_one: 'User',
      title_many: 'Users',
      id: 'Id',
      username: 'Login',
      password: 'Password',
      fullname: 'Name',
      email: 'E-mail',
      phone: 'Phone',
      active: 'Activated',
      blocked: 'Blocked',
      role: 'Role',
      created_at: 'Was created',
      active_at: 'Last online',
    },
    user_role: {
      title_one: 'User Role',
      title_many: 'Users Roles',
      id: 'Id',
      title: 'Title',
      scope: 'Scope',
      users: 'Users',
    },
    video: {
      title_one: 'Video',
      title_many: 'Videos',
      id: 'Uuid',
      title: 'Title',
      description: 'Description',
      image: 'Preview',
      progress: 'Processed',
      size: 'Size',
      width: 'Width',
      height: 'Height',
      active: 'Active',
      streams: 'Streams',
      dimension: 'Dimension',
      created_at: 'Created at',
      qualities: 'Versions',
      error: 'Processing error',
    },
    setting: {
      title: 'Title',
      title_desc: 'Project title, used on all pages',
      description: 'Description',
      description_desc: 'Brief description of the project',
      about: 'About project',
      about_desc: 'A detailed note with a story about the project, pinned to the main page',
      poster: 'Main poster',
      poster_desc: 'Project avatar, displayed on the main page',
      background: 'Poster background',
      background_desc: 'Background image for the main page',
      copyright: 'Project owner',
      copyright_desc: 'Displayed in the copyright line in the footer',
      started: 'Project start date',
      started_desc: 'The project start date is used to form the copyright line in the footer',
    },
    level: {
      title_one: 'Subscription level',
      title_many: 'Subscription levels',
      id: 'Id',
      title: 'Title',
      content: 'Description',
      price: 'Price',
      cover: 'Cover image',
      active: 'Enabled',
      per_month: 'per month',
    },
  },
  components: {
    table: {
      no_data: 'Nothing to display',
      no_results: 'Nothing found',
      records: 'No records | 1 record | {total} records',
      query: 'Search...',
      delete: {
        title: 'Confirmation required',
        confirm: 'Are you sure you want to delete this entry?',
      },
    },
    upload: {
      status_loading: 'Uploaded {uploaded} from {size}. There are {remaining} left at a speed of {speed}.',
      status_paused: 'Uploaded {uploaded} from {size}.',
      status_finished: 'Successfully uploaded {size} in {duration} at a speed of {speed}.',
      status_error: 'Unexpected error from the server: "{error}".',
    },
  },
  pages: {
    index: 'Main',
    about: 'About',
    posts: 'Posts',
    admin: {
      title: 'Admin',
      users: 'Users',
      user_roles: 'Roles',
      videos: 'Videos',
      settings: 'Settings',
      levels: 'Subscriptions',
    },
    user: {
      title: 'Account',
      profile: 'Profile',
    },
  },
  success: {
    profile: 'Profile saved successfully',
  },
  errors: {
    user: {
      no_username: 'Username is required',
      no_fullname: 'Fullname is required',
      no_email: 'Email is required',
      username_exists: 'This username is already exists',
      email_exists: 'This email is already exists',
      inactive: 'This account is not active',
      blocked: 'This account is blocked',
      delete_own: 'You can not delete yourself',
    },
    user_role: {
      delete_own: 'You cannot delete your own group',
    },
    login: {
      wrong: 'Wrong username or password',
    },
    activate: {
      no_user: 'The user does not exist or did not reset the password',
      ttl: 'The link has expired',
      wrong: 'Incorrect temporary password',
    },
    video: {
      no_image: 'You forgot to upload an image for the video',
    },
    setting: {
      required: 'This setting is required',
    },
    upload: {
      no_filename: 'Could not get the name of file',
      no_size: 'Could not get the size of file',
      missing_meta: 'Could not get upload metadata',
      wrong_offset: 'Wrong upload chunk offset',
      wrong_content: 'Wrong uploading encoding',
      write: 'File writing error',
    },
    level: {
      no_title: 'You forgot to specify the name of the subscription level',
      no_price: 'You must specify the price of the subscription',
      title_exists: 'This title already exists',
      price_exists: 'A level with this price has already been made',
    },
  },
}
